### ISSUE TITLE
[feature request / idea] support extended attribute nodump on supported platforms

### ISSUE THREAD

**Issue by efx** [dpc/rdedup#143]
As a backup program user, I have used borg backup and find [their support](https://borgbackup.readthedocs.io/en/stable/usage/general.html#support-for-file-metadata) of the `nodump` flag quite useful for doing full system backups. For the utility on Linux systems to manage extended flags, see https://linux.die.net/man/1/chattr.
It would be neat if rdedup could support this flag as well by a command line option or by default.

**Comment by dpc** [comment]
So, `rdedup` itself is data agnostic. It takes in a stream of bytes, CDC, dedup, compress, encrypt, save, and then it can restore that stream for you on another day.

Currently `rdedup` does not implement it's own dir traversing. That's why you usually pair it with `tar` or `rdup`. `rdup` supports `.nobackup` files which I personally use.

There is a https://github.com/Ralith/rackup project in the works, which uses `rdedup_lib` as a backend, and implements it's own CDC-friendly format and directory traversal. It could implement this, I think.

**Comment by efx** [comment]
ah, thanks for the clarification @dpc. After reading the README more carefully as well, I see how this issue doesn't apply to rdedupe itself. Thanks for the project; looks quite helpful for fast backups.
