### ISSUE TITLE
Analyse the `rdedup store` pipeline performance.

### ISSUE THREAD

**Issue by dpc** [dpc/rdedup#15]
Separate threads are used for reading, assembling, compression, encryption and storing. By measuring channel saturation, performance could be optimized: more threads could be used to perform bottleneck tasks, or bigger channel could be used to amortize workload.

**Comment by phillipCouto** [comment]
I am wondering if we ditch the pipelines and only have an additional thread to write out the new chunks? This would reduce syncing of data between threads as well as reduce the code complexity.

I will try to perform the benchmarks and see if there is a difference worth taking action on =)

**Comment by phillipCouto** [comment]
I was thinking that using the futures library with a cpupool over the 4 thread pipeline may be more efficient and can simplify the code as a promise would be the task of compress -> encrypt -> write instead of a thread handling a specific function.

This should also provide a more even usage of CPU resources as the intensive tasks of compress and encrypt will be distributed more evenly. This also can reduce the memory usage by only having one unit of work in memory per executing task instead of a queue between each part of the pipeline that if say the writing part is the slowest all queues are full with chunks in memory. (which is my common case)

What do you think?

**Comment by dpc** [comment]
I'm not sure if futures are giving much here. Futures are mostly beneficial when there's a lot of blocking on IO.

Definitely making sure both IO (read and write) and all  cpus are utilized should yield the best performance. Also "every worker thread doing all CPU intense steps one after another" might be better, yes.

Right now the architecture is:

    READ -> COMPRESS -> ENCRYPT -> WRITE

by having it:

          /-> COMPRESS, ENCRYPT\  
    READ-        .. N copies .. -> WRITE
          \-> COMPRESS, ENCRYPT/

we could definitely utilize more cores if IO is fast enough, without any particular upper bound (number of available CPUs is the limit).

Writes could be also done in parallel, since they write to different files.


          /-> COMPRESS, ENCRYPT, WRITE
    READ-        .. N copies ..
          \-> COMPRESS, ENCRYPT, WRITE

but it seems to me that in case writing is slow, that would unnecessarily block workers. Now, using futures the WRITE would not block and there could be N workers where N is much bigger than number of cores and they would each complete the write when possible, but that would be the same memory usage (if not greater) than channel memory output.

Also note, that AFAIK, filesystem operations are not first class async citizens, and they are usually implemented by having an underlying writer/reader thread, so effectively degrading to graph 2.

If you think I'm wrong about something, please let me know.

**Comment by dpc** [comment]
Relevant: https://www.reddit.com/r/rust/comments/5penft/parallelizing_enjarify_in_go_and_rust/

What's you opinion? I  could give it a shot.

**Comment by phillipCouto** [comment]
Yes file IO is not async as each OS implements async file io in different ways like linux needs you to open the file with DirectIO so it is unbuffered and it needs to be aligned in order for it to be async.

I was just thinking of futures because they already come with a CPU Pool to use and futures could then be adopted to work for remote file systems later and actually be async in those scenarios.

I think we should go the easy way first and make all three operations in a single unit of work. Once complete we can then try a separate pool for writes later and see if there is a difference. As it depends on the disk. If it is an ssd it may keep up, if it is a slow HDD it may be better not to have a lot of pending writes queued in memory as it increases memory consumption.

Also one thing I noticed that happens in the current and will in the thread pool design is if we don't cache lets say the most recent 256 hashes that have been sent to be written we actually send duplicates down to be stored even though there is a duplicate chunk in the queue but hasn't been fully commited to disk yet. This happens if lets say we hit a portion of a file with running duplicates off data or a copy of the same data slightly further in from the stream.

Regardless I am totally in favour of the pooled work model over the pipeline model =)

**Comment by phillipCouto** [comment]
@dpc are you still looking into this?

**Comment by dpc** [comment]
I am, indeed. Almost there.

**Comment by phillipCouto** [comment]
Oh ok sweet :)

**Comment by phillipCouto** [comment]
@dpc is this considered closed for now then?

**Comment by dpc** [comment]
I think so! We did a good job here. :)

**Comment by phillipCouto** [comment]
Hahah we? That was all you! I just reviewed it ;D
