### ISSUE TITLE
Incremental Garbage Collection

### ISSUE THREAD

**Issue by phillipCouto** [dpc/rdedup#32]
When repos get massive with large counts of chunks I think an incremental gc may be beneficial. I am think of processing the repo by using ranges on the first 2 bytes of a digest. After the run is complete we can create a file in the repo to record the last position of the gc. The next run would check the last position and work from there. Every run of the gc would scan all the reachable digests first.

Example:

The first run would scan from ```chunks/00/``` to ```chunks/0F/```, purge what is considered garbage, write the position file with a value of ```0f``` and exit.

The second run would see the file exists, verify it is within the range of a hex value and is not at the end of the range ```ff```. It would then proceed from the last position + 1 so in the case above it would scan from ```10``` to ```1f```, purge what is considered garbage, write the position file with a value of ```1f``` and exit.

This would continue till the end and then wrap to the beginning.

On my machine the list_stored_chunks to 488 seconds to scan everything. If we break the work down to smaller units it can even get to the point were the gc can be run regularly after a delete or regular backups without huge amounts of time dedicated to the process.

What do you think? Maybe make it a seperate command?

**Comment by dpc** [comment]
Yes. Right now the GC is written in a silly way, that was easiest to implement.

To know what is no longer referenced, you need to go through all index data. I see no way around that. But I guess index data that needs to be read is reasonably smaller, and that's OK. The list (HashSet) of all chunks can get quite larger, so it could be implemented as a bloomfilter or something in the future.

The biggest problem that you're trying to address is, instead of getting list of all chunks, a GC could go through chunk directory and check chunks, one by one, against list of referenced chunks. That would allow eg. breaking GC with `ctrl+c`, or setting a deadline. GC could keep a pointer of the last checked chunk, so on each subsequent call it would start traversing from the place it left of.

With that scheme a `deadline` argument could be added to `rdedup gc`, or `ctrl+c`, user-facing API wise.

**Comment by dpc** [comment]
Relevant https://github.com/dpc/rdedup/issues/75

**Comment by dpc** [comment]
Garbage collection now is incremental.
