### ISSUE TITLE
Increase chunk sizes?

### ISSUE THREAD

**Issue by phillipCouto** [dpc/rdedup#36]
Are you opposed to increasing chunk sizes? I was thinking of increasing the BUP bitsize to 20 instead of 17. This is showing some promising speed improvements on my end. I know it would impact the reuse of existing chunks in the repo but I am trying to use rdedup to backup 80-90GB of data and I am finding the chunk sizes on average are too small with lots of random small IO that is thrashing my backup drives.

**Comment by phillipCouto** [comment]
I am seeing a throughput improvement from 5 - 10 MB/s on my fastest backup drive to 30 - 40 MB/s. I am also seeing my CPU work harder due to more data available to compress and encrypt at a given time.

**Comment by phillipCouto** [comment]
This also reduces the number of chunks in the indexes as well as less chunks to process when running gc.

**Comment by phillipCouto** [comment]
I know the cost is less accurate deduping and I am willing to perform extensive testing to see the impact if you are willing to consider the change.

**Comment by dpc** [comment]
Let's make chunk sizes configurable during `rdedup init`.

The first thing would be to move current meta-files to some format like json.

**Comment by phillipCouto** [comment]
Ok JSON or TOML?

**Comment by jedisct1** [comment]
`TOML`

**Comment by dpc** [comment]
Right now I just glued nonce, salt and so on to each other and dumped them in hex form to a file, with a "repo version" number first. But since rdedup is picking up functionality, a more extendable format will be better.

I would prefer JSON. I don't expect repo metaconfiguration file to be modified by hand. It will be written once on `rdedup init` and read every time repo is opened by `rdedup-lib`. Someone might want to view it manually and some fields might be added or removed with time. TOML main benefit is editing convenience, I guess. JSON is more popular. Anyway, I'll personally accept a PR with any of them, I don't think it matters much, though I'm OK with changing my mind if there's a good reason for it.

**Comment by dpc** [comment]
I've split this into two separate issues.
