### ISSUE TITLE
Too much useless io in chunk_write due to create_dir_all()

### ISSUE THREAD

**Issue by lukaslueg** [dpc/rdedup#95]
`ChunkWriterThread::run` [currently](https://github.com/dpc/rdedup/blob/fdad57f143c9669e219533515a41047653918b43/lib/src/chunk_writer.rs#L113
) calls `create_dir_all()` twice, which is useless at best but causes quite a lot of IO.

We can reduce IO further by asking for forgivness instead of permission and moving the `create_dir_all()`-call into a new error-path for `fs::File::create(&tmp_path).unwrap();`. As the path will exist for almost all but one calls to `fs::File::create()` per `path`, we should just try to create the file directly and only create the path structure in case we fail. This saves us from *a lot* of stat64-calls.

**Comment by dpc** [comment]
The reason it's called twice is: https://github.com/rust-lang/rust/issues/33707 which I recently fixed with: https://github.com/rust-lang/rust/pull/39799 . It is yet hit `stable`, That PR also improves the the performance of `create_dir_all` and makes it "try first and check later".

You're right that it would be better to just try `File::create` first and `mkdir` only if it failed. Please submit a PR!

**Comment by dpc** [comment]
Done. https://github.com/dpc/rdedup/blob/ef746ab5acff07660108878a4b96fe4808914c03/lib/src/asyncio.rs#L408
